package utils

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
)

func IsRoot() bool {
	return os.Geteuid() == 0
}

func RequireRoot() {
	if !IsRoot() {
		fmt.Fprintln(os.Stderr, "ERROR: This utility requires root privileges. Please run with sudo.")
		os.Exit(1)
	}
}

func GetCommandOutput(command ...string) *bytes.Buffer {
	if len(command) == 0 {
		panic("Error: No command provided.")
	}

	var stdout bytes.Buffer
	cmd := exec.Command(command[0], command[1:]...)
	cmd.Stdout = &stdout

	if err := cmd.Run(); err != nil {
		panic(fmt.Sprintf("Error: Unable to run command: %s", command[0]))
	}

	return &stdout
}

func GetOrDefault[K comparable, V any](m map[K]V, key K, def V) V {
	// Helper generated by AI: ChatGPT 5.2
	if v, ok := m[key]; ok {
		return v
	}
	return def
}
